### ISSUE TITLE
Gradle task does not work with version 7.0

### ISSUE THREAD

**Issue by jgremmen** [shevek/jarjar#22]
Gradle version 7.0 now reports the following error:
`- Type 'JarjarTask' property 'destinationDir' is missing an input or output annotation.`

**Comment by ungesehn** [comment]
To be more specific about the error message given: 

> FAILURE: Build failed with an exception.
> * What went wrong:
> Some problems were found with the configuration of task ':repackaged' (type 'JarjarTask').
>   - Type 'org.anarres.gradle.plugin.jarjar.JarjarTask' property '**destinationDir**' is missing an input or output annotation.
>     
>     Reason: A property without annotation isn't considered during up-to-date checking.
>     
>     Possible solutions:
>       1. Add an input or output annotation.
>       2. Mark it as @Internal.
>     
>     Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
>   - Type 'org.anarres.gradle.plugin.jarjar.JarjarTask' property '**destinationName**' is missing an input or output annotation.
>     
>     Reason: A property without annotation isn't considered during up-to-date checking.
>     
>     Possible solutions:
>       1. Add an input or output annotation.
>       2. Mark it as @Internal.
>     
>     Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.

**Comment by ungesehn** [comment]
I tested this with a local build - the current code on GitHub is **compatible** with Gradle 7.0. However a new release of the jarjar Gradle plugin is required as the latest version is 1.0.1.

See also the request in #16

**Comment by andob** [comment]
@shevek I get a different problem, while using the JarJar Gradle Plugin with Gradle 7.0.2:

```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-all.zip
```

```
buildscript {
    dependencies {
        classpath 'org.anarres.jarjar:jarjar-gradle:1.0.1'
    }
}

apply plugin: 'org.anarres.jarjar'

dependencies {
    implementation jarjar.repackage {
        from 'org.apache.tika:tika-core:2.0.0'
        classDelete 'org.apache.tika.io.MappedBufferCleaner'
    }
}
```

Full error:

```
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/commons/RemappingClassAdapter
	at com.tonicsystems.jarjar.transform.jar.DefaultJarProcessor.<init>(DefaultJarProcessor.java:35)
	at org.anarres.gradle.plugin.jarjar.JarjarTask.<init>(JarjarTask.java:98)
	at org.anarres.gradle.plugin.jarjar.JarjarTask_Decorated.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:2032)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:480)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:88)
	... 185 more
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.RemappingClassAdapter
	... 196 more
```

JarJar Gradle version 1.0.1 seem to use an outdated ASM version, while gradle includes a more recent one. Please update the gradle plugin.

**Comment by andob** [comment]
## I just realized, we can use [jitpack.io](jitpack.io) to import the latest snapshot of the plugin (which is compatible with Gradle 7) into our projects.

**To import the plugin:**

**Legacy Gradle API:**

``build.gradle``
```
buildscript {
    repositories {
        //........................
        maven { url "https://jitpack.io" }
        //........................
    }
    dependencies {
        //........................
        classpath 'com.github.shevek.jarjar:jarjar-gradle:9a7eca72f9'
    }
}
```
``app/build.gradle``
```
apply plugin: 'org.anarres.jarjar'
```

**New Gradle API:**

``settings.gradle``
```
pluginManagement {
  repositories {
        //........................
        maven { url "https://jitpack.io" }
        //........................
  }
}
```
``app/build.gradle``
```
plugins {
    //.................
    id 'org.anarres.jarjar'
}
```

**To use the plugin:**

For instance, to import Apache Tika excluding ``org.apache.tika.io.MappedBufferCleaner`` that uses ``MethodHandle`` API which is missing on Android API level < 26:

``app/build.gradle``
```
dependencies {
    //................................................................
    implementation jarjar.repackage {
        from 'org.apache.tika:tika-core:2.1.0'
        classDelete 'org.apache.tika.io.MappedBufferCleaner'
    }
    //................................................................
}
```

@ungesehn @matthewhague @cah-anuj-shrivastava @thomasstache @AlexKrupa @cmathew @jgremmen

**Comment by ghost** [comment]
@andob Unfortunately, when I add `id("org.anarres.jarjar")`, Gradle can't fetch the plugin:
```
Plugin [id: 'org.anarres.jarjar'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
...
```

**UPD.** I've resolved it like this:
```gradle
buildscript {
    repositories {
        maven {
            url = uri("https://jitpack.io")
        }
    }
    dependencies {
        classpath("com.github.shevek.jarjar:jarjar-gradle:master")
    }
}

apply(plugin = "org.anarres.jarjar")
```

**Comment by cmeng-git** [comment]
Using master branch may cause problem in project if there a new release with conflict to your current project usage.

https://github.com/shevek/jarjar/issues/22#issuecomment-992623722

I tried your proposal. it did get rid of the warnings. However I found the following problems:
a. The new jarjar respects the defined parameters for "destinationDir" but ignore "destinationName"
b. During the AS build, it just assigned random names to the newly generated jar files e.g. in project/build/jarjar/CH_223212.jar
c. AS just keeps adding new generated jar files every time user do a build, without deleted the old one.
d. In aTalk implementation, it needs the actual defined "destinationName" as reference, so the build always failed
f. There is another serious problem when doing a "Generate Signed Bundle/APK" process, AS build failed with the following error: 

Execution failed for task ':aTalk:collectPlaystoreReleaseDependencies'.
> java.io.FileNotFoundException: /~workspace/android/atalk-android/aTalk/build/jarjar (Is a directory)

**Comment by ghost** [comment]
@cmeng-git

I'm using the current `master` and you can still assign a name to the repackaged jar, here's in Kotlin DSL:
```gradle
implementation(files(JarjarController(project).repackage("<your name>", closureOf<JarjarTask> {
    from("...")
    classDelete("...")
})))
```

**Comment by cmeng-git** [comment]
Thanks for your input. I am trying to change the following to your proposal, but gradle flagged <JarjarTask>  as unresolved symbol. Is <JarjarTask> a new plugin or meant something else?

Appreciate your advice, possibly provide an actual output for the example below.

Sorry, I am not familiar with kotlin implementation, not sure if build.gradle file allows a mixture of both existing and kotlin definitions. 

```
    implementation jarjar.repackage {
        from('org.jitsi:fmj:1.0.1-jitsi')
        destinationName "fmj-1.0.1-jitsi.jar"

        // remove extracted modules for changes
        classDelete 'net.sf.fmj.media.RegistryDefaults'
        classDelete 'javax.media.format.VideoFormat'
        classDelete 'javax.media.Manager**'
    }

===>

    implementation(files(JarjarController(project).repackage("fmj-1.0.1-jitsi.jar", closureOf<JarjarTask> {
        from('org.jitsi:fmj:1.0.1-jitsi')

        classDelete 'net.sf.fmj.media.RegistryDefaults'
        classDelete 'javax.media.format.VideoFormat'
        classDelete 'javax.media.Manager**'
    })))
```

**Comment by cmeng-git** [comment]
After going through the information on:
https://www.javatips.net/api/jarjar-master/jarjar-gradle/src/main/java/org/anarres/gradle/plugin/jarjar/JarjarTask.java

It seems that your proposed scripts has the same task implementation as the one in aTalk gradle script. So the problem of merging multiple output jars into the specified destinationName is not working using [jitpack.io](https://github.com/shevek/jarjar/issues/jitpack.io)

> @cmeng-git
> 
> I'm using the current `master` and you can still assign a name to the repackaged jar, here's in Kotlin DSL:
> 
> ```groovy-gradle
> implementation(files(JarjarController(project).repackage("<your name>", closureOf<JarjarTask> {
>     from("...")
>     classDelete("...")
> })))
> ```

**Comment by cmeng-git** [comment]
I am not sure now what my previous comment is correct.
When I changed the scripts to the following, found that 1 of 3 output *.jar indeed get renamed to "fmj-1.0.1-jitsi.jar". 
As I am not familiar with jarjar-gradle, may be someone can give me a hint on how to merged all the output jar files into one, before the file rename process.

```
    implementation jarjar.repackage("fmj-1.0.1-jitsi.jar", {
        from('org.jitsi:fmj:1.0.1-jitsi')

        // remove extracted modules for changes
        classDelete 'net.sf.fmj.media.RegistryDefaults'
        classDelete 'javax.media.format.VideoFormat'
        classDelete 'javax.media.Manager**'
    })
```

**Comment by cmeng-git** [comment]
aTalk uses jarjar master source release for android API-34 release. JarJar is fully compatible with gradle-7.x 
see https://github.com/shevek/jarjar/issues/22#issuecomment-887420425 with updates as below:
You may refer to aTalk repository for the full solution i.e. https://github.com/cmeng-git/atalk-android

**For legacy gradle API:**
```
buildscript {
    repositories {
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.github.shevek.jarjar:jarjar-gradle:9a7eca7'

        // Usually this is set in root build.gradle file: gradle-8.x requires JVM 17; aTalk max jvm is 15.
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

apply plugin: 'org.anarres.jarjar'

repositories {
    maven {
      // local defined destinationDir if required. Default save directory is build/jarjar
        url 'third_party/m2'

        // Must include these lines for gradle to use local defined destinationDir for jarjar files
        metadataSources {
            mavenPom()
            artifact()
        }
    }
}

dependencies {
    // example use in aTalk to define destinationName for the generated jarjar file
    implementation jarjar.repackage(""ice4j-3.0-SNAPSHOT.jar"") {
        from('org.jitsi:ice4j:3.0-55-g32a8aad') {
            transitive = false
        }

       // Define only if so required; default is in build/jarjar sub-directory
        destinationDir new File("${projectDir}/.....")

        // Consumer was only introduced in API-24; required for API-21
        classRename 'java.util.function.Consumer', 'org.atalk.util.function.Consumer'

        // Duration was added in API level-26; see https://github.com/JakeWharton/ThreeTenABP
        classRename 'java.time.Duration', 'org.threeten.bp.Duration'

        // Clean up and optimize call to weupnp call - reduces threads avoid time race condition
        classDelete 'org.ice4j.ice.harvest.UPNPHarvester**'
    }
}

Note: 
- Set distributionUrl=https://services.gradle.org/distributions/gradle-7.6-bin.zip in gradle-wrapper.properties;
   gradle-8.x does not generate the required smack jarjar files at all.

```
