### ISSUE TITLE
CLI doesn't work

### ISSUE THREAD

**Issue by NathanSweet** [shevek/jarjar#8]
Cloned, built with Gradle (would prefer a JAR download), run on Windows:
```
jarjar-command.bat
Exception in thread "main" java.lang.IllegalArgumentException: [output] is required.
        at com.tonicsystems.jarjar.Main.valueOf(Main.java:95)
        at com.tonicsystems.jarjar.Main.process(Main.java:130)
        at com.tonicsystems.jarjar.Main.run(Main.java:75)
        at com.tonicsystems.jarjar.Main.main(Main.java:144)
```
Same for `jarjar-command.bat help`, `jarjar-command.bat process x y z`, etc.

**Comment by NathanSweet** [comment]
The documentation says `process <rulesFile> <inJar> <outJar>` is supposed to work, but it does not. `-rules [rulesFile] -output [outputJAR] [inputJAR]` is required. `help` still doesn't work.

**Comment by JekRock** [comment]
@NathanSweet it works. Parameters should be passed with "--". For example try to run `java -jar .\jarjar.jar --help`
